### ISSUE TITLE
Getting started instructions should not assume that pip exists

### ISSUE THREAD

**Issue by ofrobots** [googleapis/releasetool#145]
#### Environment details

  - OS: Linux debian
  - Python version: 3.5.3
  - pip version: none installed
  - `releasetool` version: none installed

#### Steps to reproduce

  1. Follow installation instructions from the README. 
  2. Installation fails if pip isn't already installed.

`releasetool` assume that either the use already has `pip` or is knowledgeable enough about python to be able to install `pip`. 

```sh
$ python3 -m pip install --user --upgrade gcp-releasetool
/usr/bin/python3: No module named pip
```

It would be really nice if the README could provide instructions on how to proceed here :smile_cat:

**Comment by theacodes** [comment]
Lack of pip can happen if you're using an os provided Python interpreter.
This can be tricky, so I suggest following the hitchhiker's guide to python
for this. We can totally link to it from the readme.


https://docs.python-guide.org/starting/install3/linux/


It is hysterically almost easier usually to build python from source into
~/. local so that you never run afoul of the os interpreter.
