### ISSUE TITLE
Tag job is failing for GoogleCloudPlatform/terraform-google-cloud-run

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/releasetool#347]
```
Triggering cloud-devrel/client-libraries/python/googleapis/python-retail/release/release using v0.3.0
Processing chore: release 0.1.0: https://github.com/GoogleCloudPlatform/terraform-google-cloud-run/pull/15
Closed, not merged, skipping.
HTTPError('403 Client Error: Forbidden for url: https://api.github.com/repos/GoogleCloudPlatform/terraform-google-cloud-run/issues/15/labels')
```

**Comment by tmatsuo** [comment]
Example build: https://source.cloud.google.com/results/invocations/d591fe99-6115-41f2-90b6-e23d806b3dd9/log

**Comment by busunkim96** [comment]
I believe the error is from releasetool trying to modify PRs in GoogleCloudPlatform repos it lacks permissions for. Since release-please completes the release (https://github.com/GoogleCloudPlatform/terraform-google-cloud-run/releases/tag/v0.1.0) this is only a problem with respect to how it is marked "failed" in the log.

Lowering the priority to P2.
